#define SL_MENU_ITEM_TYPE_NORMAL					 0
#define SL_MENU_ITEM_TYPE_SEPARATOR				 1
#define SL_MENU_ITEM_TYPE_CHECK					 2
#define SL_MENU_ITEM_TYPE_RADIO					 3
#define SL_MENU_ITEM_TYPE_QUIT					 4
#define SL_MENU_ITEM_TYPE_ABOUT					 5
#define SL_MENU_ITEM_TYPE_PREFERENCES			 6
#define SL_MENU_ITEM_TYPE_APPLICATION			 7