#define SL_TOOLBAR_STYLE_TEXT					 0x1
#define SL_TOOLBAR_STYLE_ICON					 0x2
#define SL_TOOLBAR_STYLE_HORIZONTAL			 0x0
#define SL_TOOLBAR_STYLE_VERTICAL				 0x4
#define SL_TOOLBAR_STYLE_DEFAULT				 STYLE_TEXT | STYLE_ICON