#define SL_EVENT_DRAG_ACTION_NONE				 0x0
#define SL_EVENT_DRAG_ACTION_MOVE				 0x1
#define SL_EVENT_DRAG_ACTION_COPY				 0x2
#define SL_EVENT_DRAG_ACTION_CUSTOMIZABLE		 0x4
#define SL_EVENT_DRAG_ON_ITEM					 0
#define SL_EVENT_DRAG_ABOVE_ITEM					 1
#define SL_EVENT_DRAG_BELOW_ITEM					 2
#define SL_EVENT_DRAG_ON_VIEWPORT				 3