#define SL_SIZER_ITEM_EXPAND						 0x1
#define SL_SIZER_ITEM_KEEP_ASPECT_RATIO			 0x2
#define SL_SIZER_ITEM_BORDER_TOP					 0x1
#define SL_SIZER_ITEM_BORDER_BOTTOM				 0x2
#define SL_SIZER_ITEM_BORDER_LEFT					 0x4
#define SL_SIZER_ITEM_BORDER_RIGHT				 0x8
#define SL_SIZER_ITEM_BORDER_ALL					 0xF